# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

format = """$python$directory$git_branch
$character"""

right_format = '$time'
continuation_prompt = '└─>'

[character]
success_symbol = '[»](bold green)'
error_symbol = '[»](bold red)'

[directory]
truncation_length = 5
style = 'bold cyan'

[package]
disabled = true

[time]
disabled = false
format = '[\[$time\]]($style)'
style = 'bold yellow'

[git_branch]
format = '[on $branch]($style)'
style = 'bold purple'

[python]
format = '(<${virtualenv}>) ($style)'
style = 'yellow'

